export const FETCH_PORTFOLIO_LIST_SUCCESS = 'PORTFOLIOS/FETCH_PORTFOLIO_LIST_SUCCESS';
export const FETCH_PORTFOLIO_LIST_ERROR = 'PORTFOLIOS/FETCH_PORTFOLIO_LIST_ERROR';
export const CLEAR_FETCH_PORTFOLIO_LIST = 'PORTFOLIOS/CLEAR_FETCH_PORTFOLIO_LIST';

export const FETCH_PORTFOLIO_DETAILS_SUCCESS = 'PORTFOLIOS/FETCH_PORTFOLIO_DETAILS_SUCCESS';
export const FETCH_PORTFOLIO_DETAILS_ERROR = 'PORTFOLIOS/FETCH_PORTFOLIO_DETAILS_ERROR';
export const CLEAR_FETCH_PORTFOLIO_DETAILS = 'PORTFOLIOS/CLEAR_FETCH_PORTFOLIO_DETAILS';
