export const SITE_LOADING = 'COMMON/SITE_LOADING';

export const NOT_FOUND = 'COMMON/NOT_FOUND';
export const RESET_NOT_FOUND = 'COMMON/RESET_NOT_FOUND';

export const SET_ACTIVE_PAGE = 'COMMON/SET_ACTIVE_PAGE';
export const RESET_ACTIVE_PAGE = 'COMMON/RESET_ACTIVE_PAGE';
