export const REGISTRATE_USER_SUCCESS = 'USERS/REGISTRATE_USER_SUCCESS';
export const REGISTRATE_USER_ERROR = 'USERS/REGISTRATE_USER_ERROR';
export const CLEAR_REGISTRATE_USER = 'USERS/CLEAR_REGISTRATE_USER';

export const LOGGED_IN = 'USERS/LOGGED_IN';
export const LOGIN_ERROR = 'USERS/LOGIN_ERROR';
export const CLEAR_LOGIN_ERROR = 'USERS/CLEAR_LOGIN_ERROR';

export const FETCH_ME = 'USERS/FETCH_ME';
export const FETCH_ME_ERROR = 'USERS/FETCH_ME_ERROR';

export const LOGGING_OUT = 'USERS/LOGGING_OUT';
export const LOGGED_OUT = 'USERS/LOGGED_OUT';
