export const FETCH_EXCHANGE_LIST_SUCCESS = 'EXCHANGES/FETCH_EXCHANGE_LIST_SUCCESS';
export const FETCH_EXCHANGE_LIST_ERROR = 'EXCHANGES/FETCH_EXCHANGE_LIST_ERROR';
export const CLEAR_FETCH_EXCHANGE_LIST = 'EXCHANGES/CLEAR_FETCH_EXCHANGE_LIST';
